### ISSUE TITLE
Why not Object.fromEntries

### ISSUE THREAD

**Issue by mathe42** [hugojosefson/to-object#1]
```ts
Object.fromEntries([  ["Alice", "11111111"],["Eve", "44444444"],["Bob", "22222222"]])
```
Gets the same result as in the readme?

> I looked through some deno.land/x packages and wondered why this package exists...

**Comment by hugojosefson** [comment]
That's right! I noticed `Object.fromEntries` too, just a few days ago. And I use it already in one codebase :)

I should deprecate this module, and recommend using the built-in function instead.

Thank you for the reminder!
